# Generated by Django 5.0.4 on 2024-06-07 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('academic_key', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id_permission', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=40)),
                ('permission_name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='RoleWeb',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('rolname', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=25)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'role_web',
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('academic_key', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'UserData',
            },
        ),
        migrations.CreateModel(
            name='RolePermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_permission_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.permissions')),
                ('id_rol_web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.roleweb')),
            ],
            options={
                'db_table': 'role_permissions',
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id_log_activity', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_log_activity',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('id_rol_web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.roleweb')),
                ('id_user_web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_role',
            },
        ),
    ]
