# Generated by Django 5.0.4 on 2024-06-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleweb',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
