# Generated by Django 5.0.4 on 2024-06-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_roleweb_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='actionsDict',
            fields=[
                ('id_action', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'dictionary_actions',
            },
        ),
        migrations.RenameField(
            model_name='rolepermissions',
            old_name='id_permission_data',
            new_name='id_permission',
        ),
        migrations.RenameField(
            model_name='rolepermissions',
            old_name='id_rol_web',
            new_name='id_rol',
        ),
        migrations.RenameField(
            model_name='useractivitylog',
            old_name='user',
            new_name='id_user',
        ),
        migrations.RenameField(
            model_name='userrole',
            old_name='id_rol_web',
            new_name='id_rol',
        ),
        migrations.RenameField(
            model_name='userrole',
            old_name='id_user_web',
            new_name='id_user',
        ),
        migrations.AddField(
            model_name='userdata',
            name='institutional_email',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='personal_email',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
