# Generated by Django 5.0.4 on 2024-05-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='permission_name',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
