# Generated by Django 5.0.4 on 2024-05-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_permissions_permission_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
