# Generated by Django 5.0.4 on 2024-06-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_userdata_status_alter_userrole_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='academic_key',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
